package com.all.products.models;
// Generated Dec 6, 2018 12:29:21 AM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Package generated by hbm2java
 */
@Entity
@Table(name = "package", catalog = "activent_products")
public class ProductPackage implements java.io.Serializable {

	private long packageId;
	private Date dtCreate;
	private Date dtUpdate;
	private String packageName;
	private long productId;
	private long organizationId;
	private long rating;
	private String processingFees;
	private String emi;
	private String maxLoanAmt;
	private String tenure;
	private long isActive;

	public ProductPackage() {
	}

	public ProductPackage(Date dtCreate, Date dtUpdate) {
		this.dtCreate = dtCreate;
		this.dtUpdate = dtUpdate;
	}

	public ProductPackage(Date dtCreate, Date dtUpdate, String packageName, long productId, long organizationId, long rating,
			String processingFees, String emi, String maxLoanAmt, String tenure, long isActive) {
		this.dtCreate = dtCreate;
		this.dtUpdate = dtUpdate;
		this.packageName = packageName;
		this.productId = productId;
		this.organizationId = organizationId;
		this.rating = rating;
		this.processingFees = processingFees;
		this.emi = emi;
		this.maxLoanAmt = maxLoanAmt;
		this.tenure = tenure;
		this.isActive = isActive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PACKAGE_ID", unique = true, nullable = false)
	public long getPackageId() {
		return this.packageId;
	}

	public void setPackageId(long packageId) {
		this.packageId = packageId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_CREATE", nullable = false, length = 19)
	public Date getDtCreate() {
		return this.dtCreate;
	}

	public void setDtCreate(Date dtCreate) {
		this.dtCreate = dtCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_UPDATE", nullable = false, length = 19)
	public Date getDtUpdate() {
		return this.dtUpdate;
	}

	public void setDtUpdate(Date dtUpdate) {
		this.dtUpdate = dtUpdate;
	}

	@Column(name = "PACKAGE_NAME")
	public String getPackageName() {
		return this.packageName;
	}

	public void setPackageName(String packageName) {
		this.packageName = packageName;
	}

	@Column(name = "PRODUCT_ID")
	public long getProductId() {
		return this.productId;
	}

	public void setProductId(long productId) {
		this.productId = productId;
	}

	@Column(name = "ORGANIZATION_ID")
	public long getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(long organizationId) {
		this.organizationId = organizationId;
	}

	@Column(name = "RATING")
	public long getRating() {
		return this.rating;
	}

	public void setRating(long rating) {
		this.rating = rating;
	}

	@Column(name = "PROCESSING_FEES")
	public String getProcessingFees() {
		return this.processingFees;
	}

	public void setProcessingFees(String processingFees) {
		this.processingFees = processingFees;
	}

	@Column(name = "EMI")
	public String getEmi() {
		return this.emi;
	}

	public void setEmi(String emi) {
		this.emi = emi;
	}

	@Column(name = "MAX_LOAN_AMT")
	public String getMaxLoanAmt() {
		return this.maxLoanAmt;
	}

	public void setMaxLoanAmt(String maxLoanAmt) {
		this.maxLoanAmt = maxLoanAmt;
	}

	@Column(name = "TENURE")
	public String getTenure() {
		return this.tenure;
	}

	public void setTenure(String tenure) {
		this.tenure = tenure;
	}

	@Column(name = "IS_ACTIVE")
	public long getIsActive() {
		return this.isActive;
	}

	public void setIsActive(long isActive) {
		this.isActive = isActive;
	}

}
